// <auto-generated />
namespace W2022A6YH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class rich_text : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rich_text));
        
        string IMigrationMetadata.Id
        {
            get { return "202204142009007_rich_text"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
